AppTitle = "Chess pgn reviser"
BlackWon = "Black has won by checkmate."
Draw = "Draw."
GameFinished = "Game finished"
WhiteWon = "White has won by checkmate."
promotionDialogDismissButton = "Cancel"
promotionDialogTitle = "Choose the promotion piece :"
